# Generated by Django 3.2.5 on 2021-08-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Activae'), ('deactive', 'Deactivae')], default='active', max_length=10),
        ),
    ]
